package IanCoranguez;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.util.Random;

@EqualsAndHashCode
public class Assignment {
    //fields
    @Getter
    private final String assignmentId;
    @Getter @Setter
    private String assignmentName;
    @Getter @Setter
    private double weight;
    @Getter
    private double avgScore;
    private ArrayList<Integer> scores = new ArrayList<>();
    private static int nextId = 0;
    private static final Random rand = new Random();

    /**
     * creates a new Assignment object, based on the parameters it will also generate an ID, fill its scores list with random scores, and it will also calculate
     * the average for this assignment
     * @param assignmentName The assignment name, for example Assignment01
     * @param weight The weight of the assignment, this has to be in the range from 0.0 to 1.0,
     *               if it is bigger than 1 it will just create a new assignnment with 1
     *               as weight, if it is negative it will just take 0
     * @param amountStudInCourse the amount of students in this assigment's course, this is not a field per se,
     *                          this is just to know how many scores have to be generated by default
     */
    public Assignment(String assignmentName, double weight, int amountStudInCourse) {
        this.assignmentName = assignmentName;
        this.weight = Math.max(Math.min(1.0, weight), 0.0);
        this.assignmentId = String.format("%04d", nextId++);
        fillScoresRandom(amountStudInCourse);
        calcAssignmentAvg();
    }



    /**
     * This will fill the scores list with random scores
     * @param amountScoresNeeded the amount of scores that have to be genarated
     */
    public void fillScoresRandom(int amountScoresNeeded) {
        scores.clear();
        for (int i = 0; i < amountScoresNeeded; i++) {
            scores.add(generateRandomScore());
        }
    }
    /*
    I splited these two functions to be able to re-use generateRandom score if needed, for example if we want to implement a new method that sets
    an student score individually, this will be save some time since we wouldn't have to write this again, plus we can change the general logic of
    a random score generation in just one place.
    */

    /**
     * generates a semi-random score in the range from 0 to 100, it is designed to be likely to generate high scores
     * @return the random score
     */
    public int generateRandomScore() {
        return switch (rand.nextInt(11)) {
            case 0 -> rand.nextInt(0,60);
            case 1, 2 -> rand.nextInt(60,70);
            case 3, 4 -> rand.nextInt(70, 80);
            case 5, 6, 7, 8 -> rand.nextInt(80, 90);
            default -> rand.nextInt(90, 101);
        };
    }

    /**
     * calculates the average of all the scores in the scores list
     */
    private void calcAssignmentAvg() {
        avgScore = 0;

        if (scores.isEmpty()) {
            return;
        }

        for (Integer score : scores) {
            if (score == null) {
                continue;
            }
            avgScore += score;
        }

        avgScore /= scores.size();
    }

    /**
     * adds a new score to the scores list and updates the average
     * @param score the score to be added to the score list
     */
    public void addScore(Integer score) {
        scores.add(score);
        calcAssignmentAvg();
    }

    /**
     * removes the score at the given index of the score list and updates the average.
     *
     * @param idx the index of the score to be deleted
     */
    public void removeScore(int idx) {
        if (idx > scores.size() - 1 || idx < 0){
            return;
        }

        scores.remove(idx);
        calcAssignmentAvg();

    }

    /**
     * describes the assignment as a string, it just shows the assignmentName, assignmentId and the weight
     * @return the object described as a string
     */
    public String toString() {
        return String.format("Assignment{ name = %s id = %s weight = %s}", assignmentName, assignmentId, weight);
    }

    //this just makes sure that the average stays relevant and eliminates the risk of accidentally messing it up
    public ArrayList<Integer> getScores() {
        return new ArrayList<>(scores);
    }
}
